# Site settings
title: Bo Vandersteene
description: Software architect. Coach people with the newest technologies
url: http://www.reibo.io
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: bovandersteene

author:
  name: 'Bo Vandersteene'
  email: bo@reibo.io
  twitter_username: reibo_bo
  github_username:  bo.vandersteene
  linkedin_username:   bo.vandersteene

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed